---
title: "Preliminary Comparison of RSE and DS Competences"
keywords: [Research Software-Engineering, Data Science, Competences]
abstract: |
  Die LaTeX-Klasse `lni` setzt die Layout-Vorgaben f체r Beitr채ge in LNI Konferenzb채nden um.
  Dieses Dokument beschreibt ihre Verwendung und ist ein Beispiel f체r die entsprechende Darstellung.

format:
  pdf:
    template: quarto-lni-template.tex
    documentclass: lni
    classoption: [english, biblatex]
    cite-method: biblatex
    keep-tex: true
    pdf-engine: pdflatex
    biblio-style: lni
    bibliography: my-paper.bib
    include-in-header:
      - text: |
          $highlighting-macros$

---

# Introduction
Computers and software have become vital elements of the research process across almost all domains. They enable researchers to collect and process ever-increasing amounts of data, simulate a wide range of phenomena on previously unexplored scales, and discover previously inconceivably complex structures in nature and societies via machine learning (ML).
This importance of computation and digitally-aided data analysis in research means that digital skills are now required by researchers at all career levels.
However, as there are more digital skills than an individual reseracher can master to perfection, there is an increasing demand for specialized support personnel that interfaces between researchers and their digtial tools, and provides targeted help and additional expertise when needed. Below we introduce some of usch roles that have emerged in the research landscape (roughly in the order in which the terms started appearing).

- **Research data managers** (also aka data stewards) are responsible for overseeing the lifecycle of research data, from its creation and collection to its storage, sharing, and preservation \cite{https://doi.org/10.5281/zenodo.4915861}.
  They are responsible for organizing, storing, and maintaining the integrity of data collected during research projects. They develop and implement data management plans, ensuring data is accurate, secure, and compliant with legal and ethical standards in order to
  improve the handling of research data at every point in the data cycle (FIXME: Insert picture of data cycle).
  They work closely with researchers to support data collection, cleaning, documentation, and sharing. Additionally, research data managers often facilitate data archiving and ensure that data is accessible for future use or replication.
  Within Germany, numerous regional networks have been formed. More information can be found at \cite{fdminfo}.

- **Data scientists** are professionals who combine expertise in programming, statistics, machine learning, and domain knowledge to analyze and interpret complex data, particularly to uncover patterns, trends, and insights from large datasets. Data scientists often build predictive models, design experiments, and communicate results through visualizations and reports.
  In academia, data scientists collaborate with faculty on academic research projects, applying data analysis techniques to disciplines like social science, biology, or education. However, data scientists also often work in companies to derive insights from corporate data and support business decisions.
  Political representation in Germany is facilitated by the "German Data Science Society" \cite{gds}.

- **Research software engineers (RSEs)** combines expertise in software development with an understanding of research processes and academic goals \cite{https://doi.org/10.5281/zenodo.495360}. They develop, maintain, and improve the software that underpins modern research, ensuring it is reliable, reproducible, sustainable, and fit for scientific purposes.
  RSEs may work within one of the increasing number of research software engineering teams that have been set up at universities and research organisations over the past decade, or they may be embedded within a research team. They may have a job title that officially recognises them as an RSE, or they may have a standard research or technical job title such as Research Assistant, Research Fellow, or Software Engineer.
  Regardless of their job title, RSEs share a set of core skills that are required to design and develop research software, understand the research environment, and ensure that they produce sustainable, maintainable code that supports reproducible research outputs, following the Findability, Accessibility, Interoperability and Reusability (FAIR) principles \cite{https://doi.org/10.12688/f1000research.157778.1}.
  RSEs have organised themselves in various national societies, in Germany this is de-RSE e.V \cite{derseev}.

While there is overlap between all these fields, we can summarise that RSEs focus on the creation of software in order to facilitate research using their SE skills.
Research data manageners focus on the data that is generated during the research process and provide infrastructure for better provisioning of the data.
Data Scientists focus on gaining insight from the data that is generated somewhere .

In this paper we focus on the competencies of RSEs and the data scientists.
(WHY?!)
Similar to Research Software Engineering (RSE), Data Science (DS) is a cross-cutting field that focuses on a special area within the sciences or data oriented businesses.

The major computing organizations ACM and IEEE published a joint recommended computing curriculum which already included data science: the Computing Curriculum 2020 [@CC2020] already lists DS as one of the special cases for computing competences.
Whilst DS is mentioned, research software engineering was absent.

There are existing bodies of knowledge (BOKs) for both software engineering [@SWEBOK2014] and data science [@DSBOK2017], each offering a comprehensive mapping of knowledge areas among themselves and in relation to the ACM computing curriculum.
However, the connection between competencies and the corresponding knowledge canon remains complex and nuanced.
Some competencies are almost the equivalent to a knowledge based learning goal whereas others integrate several knowledge areas with active application skills.
For the intent of this paper the additional mapping of knowledge areas to competency would be out of scope. However, the idea of outlining the fields and mapping corresponding aspects can be transferred analogously.

The DS-BOK maps data science not only to software engineering but also to (research) data management (RDM). This is interesting as RDM is another intersecting cycle.

Depending on the point of view RSE could be conceived as a subclass of DS or the other way around. In contrast, it takes a closer look on the interlinkage between the fields taking account of both the common competencies needed to be successful and the competencies that are specific to one of the areas.

(AND WHAT DOES THIS PAPER CONTRIBUTE? SUMMARIZE KEY INSIGHTS/FINDINGS HERE.)

The paper is structured as follows. ...

{{< include research_process.qmd >}}

# Method

In the following the contents of [@GI2021DataScience] is parsed as the most current examples
of data science curricula in the German research context. The contents are inspected for obvious links to the research process
and interpreted if no explicit connections are made. Further sources for data science curriculum is the output of the Edison Project [@EDSF2017] and the OpenDS4all Project [@OpenDS4All2020].

For the RSE side the contents of [@Goth2024RSE] are used as a basis as well as the current state of the RSE-Curriculums project [@RSECurriculums2021]. For the RSE competencies the RSE community has developed short codes. These are attached in the glossary in the attached repository [@ds2rse2025].

In addition, relevant competences from the research data management field [@petersen_2025_15025246] are included as they intersect with both DS and RSE.

In terms of methodology it should be noted that this approach follows a community-driven consensus building. It should not be mistaken for a review study with measurable intersubjectivity based on instruments like PRISMA [@Page2021PRISMA].

The lists of extracted DS and RSE competency clusters can be found in [@ds2rse2025]. We also plan to publish a full table of RSE competencies (and possible DS competencies) sorted by clusters. In terms of this top-level discussion the competency clusters are sufficient to compare the differences with regard to the research cycle.

# Results and Discussion

{{< include discussion.qmd >}}

# Conclusion

(planned/potential future work on this)


\printbibliography
