---
title: "The difference between RSE and Data Science"
keywords: [LNI Guidelines, LaTeX Vorlage]
abstract: |
  Die LaTeX-Klasse `lni` setzt die Layout-Vorgaben f체r Beitr채ge in LNI Konferenzb채nden um.
  Dieses Dokument beschreibt ihre Verwendung und ist ein Beispiel f체r die entsprechende Darstellung.

format:
  pdf:
    template: quarto-lni-template.tex
    documentclass: lni
    classoption: [english, biblatex]
    cite-method: biblatex
    keep-tex: true
    pdf-engine: pdflatex
    biblio-style: lni
    bibliography: my-paper.bib
    include-in-header:
      - text: |
          $highlighting-macros$

---


# What has been discussed

When discussing competences for research software engineers as the basis of a curriculum to train Research Software engineers (RSE) professionals it is logical to look at the data science movement for inspiration. Similar to RSE, Data Science (DS) is a cross-cutting field that focuses on a special area within the sciences or data oriented businesses.

The major computing organizations ACM and IEEE published a joint recommended computing curriculum which already included data science: the [cc2020 Computing Curriculum](https://www.acm.org/binaries/content/assets/education/curricula-recommendations/cc2020.pdf) already lists DS as one of the special cases for computing competences. Whilst DS is mentioned, research software engineering was absent.

Depending on the point of view RSE could be conceived as a subclass of DS or the other way around. In contrast, it takes a closer look on the interlinkage between the fields taking account of both the common competencies needed to be successful and the competencies that are specific to one of the areas.

TODO insert previous research to RSE and DS:
Levels of Differences between RSE and DS:

- institutional
- disciplinary connections
- target groups
- political history

{{< include research_process.qmd >}}

# Comparative Analysis of DS and RSE Competencies

In the following the contents of [@GI2021DataScience] is parsed as the most current examples
of data science curricula in the German research context. The contents are inspected for obvious links to the research process
and interpreted if no explicit connections are made.

For the RSE side the contents of [@Goth2024RSE] are used as a basis as well as the current state of the [RSE-Curriculums project](https://github.com/juliandehne/RSE-Masters/blob/main/curriculum.md). For the RSE competencies the RSE community has developed short codes. These are attached in the glossary in the appendix.

In addition, relevant competences from the research data management field [@petersen_2025_15025246] are included as they intersect with both DS and RSE.

In terms of methodology it should be noted that this approach follows a community-driven consensus building. It should not be mistaken for a review study with measurable intersubjectivity based on instruments like [PRISMA](https://www.prisma-statement.org).

The lists of extracted DS and RSE competency clusters can be found in Appendix. We also plan to publish a full table of RSE competencies (and possible DS competencies) sorted by clusters. In terms of this top-level discussion the competency clusters are sufficient to compare the differences with regard to the research cycle.

{{< include discussion.qmd >}}

\printbibliography

# Appendix {#sec:appendix}

{{< include glossary.qmd >}}

{{< include ds2rse_curriculas.qmd >}}

{{< include ds2rse_curriculas2.qmd >}}